import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("ranks real AMap candidates before asking AI to compose plans", async () => {
  const [api, page, monitoring] = await Promise.all([
    readFile(new URL("../app/api/inspiration/route.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../lib/service-monitoring.ts", import.meta.url), "utf8"),
  ]);

  assert.ok(api.indexOf("searchAmapCandidates(amapKey, safeInput, learnedPreferences)") < api.indexOf("generatePlans(aiHubMixKey, safeInput, weather, candidates, aiConfig)"));
  assert.match(api, /Promise\.all\(intents\.map/);
  assert.match(api, /const bestById = new Map/);
  assert.match(api, /right\.score - left\.score/);
  assert.match(api, /districtSource === "manual"/);
  assert.match(api, /sortrule", "weight"/);
  assert.match(api, /placeId 必须从下方真实地点候选编号中选择/);
  assert.match(api, /usedPlaceIds\.add/);
  assert.match(api, /candidateFallbackBody/);
  assert.match(api, /REAL_PLACE_FALLBACK/);
  assert.match(api, /buildCandidateFallbackPlans/);
  assert.match(api, /recommendationReasons: scored\.reasons/);
  assert.match(api, /rating >= 4\.5 \? 20/);
  assert.match(api, /totalCost > band\.max/);
  assert.match(api, /budgetEligible: false/);
  assert.match(api, /budgetLabel: clean\(input\.budget/);
  assert.match(api, /预算是目标区间/);
  assert.match(api, /\["¥100以内", "¥100–300", "¥300\+"\]\.includes/);
  assert.match(api, /\{ min: 300, max: Infinity \}/);
  assert.match(api, /distance > input\.radius/);
  assert.match(api, /input\.radius >= 10_000/);
  assert.match(api, /diversifyCandidates/);
  assert.match(api, /brandKey/);
  assert.match(api, /composePlacesForBudget/);
  assert.match(api, /routeDistance\(primary, place\) <= 3_000/);
  assert.match(api, /includedPlaces: composition\.included/);
  assert.match(api, /highBudget.*餐厅.*剧院/s);
  assert.match(api, /page_size", "25"/);
  assert.match(api, /page_num", String\(pageNumber\)/);
  assert.match(api, /firstPage\.rawCount === 25/);
  assert.match(api, /candidateSearchIntents/);
  assert.match(api, /\.slice\(0, 10\)/);
  assert.match(api, /\.slice\(0, 14\)/);
  assert.match(api, /\.slice\(0, 60\)/);
  assert.match(api, /count >= 10/);
  assert.match(api, /LiveHouse/);
  assert.match(api, /沉浸式体验.*香水手作.*银饰工坊.*玻璃工坊.*马术.*室内滑雪.*攀岩/s);
  assert.match(api, /优先新奇体验类活动/);
  assert.match(api, /儿童\|少儿\|幼儿\|亲子/);
  assert.match(api, /AI_TIMEOUT_MS = 20_000/);
  assert.match(api, /loadLearnedPreferences/);
  assert.match(api, /learnedPreferenceScore/);
  assert.match(api, /recordServiceRuns/);
  assert.match(monitoring, /fallback_triggered/);
  assert.match(api, /usedCategories/);
  assert.match(api, /morePlans/);
  assert.match(api, /buildCandidateFallbackPlans\(input, candidates, 12\)/);
  assert.match(api, /excludePlaceIds/);
  assert.match(api, /excludeCategories/);
  assert.match(api, /pool: candidateSearch\.pool/);
  assert.match(api, /matchesCategory/);
  assert.match(api, /手机\|电脑\|家电\|汽车/);
  assert.match(api, /compositionChanged/);
  assert.match(api, /budgetMatch: "under"/);
  assert.match(api, /暂停营业\|停止营业\|已关闭\|永久关闭/);
  assert.match(page, /districtSource:district\.trim\(\)\?"manual":"none"/);
  assert.match(page, /为什么推荐这里/);
  assert.match(page, /AI 暂时繁忙，已根据真实地点生成可执行方案/);
  assert.match(page, /recommendationReasons\.slice\(0,2\)/);
  assert.match(page, /本次安排总预算/);
  assert.match(page, /价格待确认/);
  assert.match(page, /预算偏好/);
  assert.match(page, /搜索范围/);
  assert.match(page, /已知地点消费约/);
  assert.match(page, /商圈搜索/);
  assert.match(page, /未达到预算偏好/);
  assert.match(page, /已从高德返回的/);
  assert.doesNotMatch(page, /先看简短说明，需要时再展开/);
  assert.match(page, /方案简介/);
  assert.match(page, /完整方案介绍/);
  assert.match(page, /活动方向 · 地点待核验/);
  assert.match(page, /通常在 30 秒内完成；超时会自动采用备用方案/);
  assert.match(page, /共同安排仍需双方分别确认/);
  assert.match(page, /本批还有/);
  assert.match(page, /换一批/);
  assert.match(page, /replaceSelectedPlan/);
  assert.match(page, /✓ 合适.*不合适.*太远.*太贵.*不新奇.*不符合状态.*地点不准确/s);
  assert.match(page, /\/api\/recommendation-feedback/);
  assert.match(page, /selectUnseenPlans/);
  assert.match(page, /反馈会用于调整你后续看到的排序/);
  assert.doesNotMatch(page, /format\(260\)/);
});
